---
title: "Home"
output:
  html_document:
    toc: false
---
```{r, echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(DT)
library(knitr)
library(kableExtra)
library(htmlTable)

all_week_stats <- read_delim("/Users/noahknoblauch/Baseball/all_week_stats.txt",delim="\t")

Scoreboard <- all_week_stats %>% group_by(real_name,week) %>% summarise(total=sum(roto_points))

Scoreboard <- arrange(Scoreboard,week)
winners<- Scoreboard %>% group_by(week)%>%filter(total==max(total))%>%filter(week!=22,week!=23,week!=24)
winners <- rename(winners,Manager=real_name,Week=week,ROTO=total)
winner_total <- winners %>% group_by(Manager)%>% summarise(Weeks_Won = n())%>% arrange(desc(Weeks_Won))


```



In Yahoo Fantasy Baseball there are two different types of league formats.  Head to Head and ROTO.  In a H2H league you only compete agianst one other manager each week. And in A ROTO league you compete against the whole league for the entire year.

I like the H2H league because it keeps you excited week in and week out because you want to do better than your opponent.  The downside is that you could have the second most stats, in the league, that week and still lose to your opponent.  

The ROTO league is nice because it shows you whose team accumulated the most stats, however it is hard to stay excited for the whole year.


My idea is to create a weekly ROTO league where each week the entire league face off.  It is the same scoring as ROTO except that after each week the stats reset.  


The code for gathering data from Yahoo is explined here [Code](Code.html)


The stats from every week can be found here [Week_Stats](Week_One.html)

The Results can be found here [Results](results.html)

