---
title: "Weekly Stats"
output: 
  html_document:
    toc: false
---

These are the stats from every team each week. With a Roto column added to show how many roto points each team recieved. 

```{r, echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(DT)
all_week_stats <- read_delim("/Users/noahknoblauch/Dropbox/Baseball/all_week_stats.txt",delim="\t",guess_max=10000)

```

```{r echo=FALSE,message=FALSE}
all_week_stats <- all_week_stats %>%
  filter(Stat != "Hits / At Bats", Stat != "IP")%>%
  mutate(stat_value=as.numeric(stat_value)) %>%
  group_by(Stat,week)%>%
  mutate(roto_points=ifelse(Stat =="WHIP"|Stat=="ERA",rank(-stat_value),rank(stat_value)))


regular_season_stats <-all_week_stats%>%
  filter(week !=22,week!=23,week!=24)

Scoreboard <- regular_season_stats%>%
  group_by(real_name,week)%>%
  summarise(ROTO=sum(roto_points))%>%
  arrange(week)

winners <- Scoreboard %>%
  group_by(week)%>%
  filter(ROTO==max(ROTO))
  
winner_total <- winners%>%
  group_by(real_name)%>% summarise(weeks_won = n())%>% arrange(desc(weeks_won))
  
week_value<-list()

for (i in 1:21){
  week<- all_week_stats%>% filter(week==i)%>%select(real_name,Stat,stat_value)
  df <- spread(week,Stat,stat_value)

  week_roto <-Scoreboard %>%filter(week==i)%>%select(ROTO,real_name)
  week_stats <- inner_join(df,week_roto,by="real_name")
  week_value[[i]] <-week_stats
}



```



# Week 1
```{r,echo=FALSE}
datatable(week_value[[1]],rownames = FALSE)

```

# Week 2

```{r,echo=FALSE}
datatable(week_value[[2]],rownames = FALSE)
```


# Week 3
```{r,echo=FALSE}
datatable(week_value[[3]],rownames = FALSE)

```

# Week 4

```{r,echo=FALSE}
datatable(week_value[[4]],rownames = FALSE)
```

# Week 5
```{r,echo=FALSE}
datatable(week_value[[5]],rownames = FALSE)

```

# Week 6

```{r,echo=FALSE}
datatable(week_value[[6]],rownames = FALSE)
```


# Week 7
```{r,echo=FALSE}
datatable(week_value[[7]],rownames = FALSE)

```

# Week 8

```{r,echo=FALSE}
datatable(week_value[[8]],rownames = FALSE)
```

# Week 9
```{r,echo=FALSE}
datatable(week_value[[9]],rownames = FALSE)

```

# Week 10

```{r,echo=FALSE}
datatable(week_value[[10]],rownames = FALSE)
```


# Week 11
```{r,echo=FALSE}
datatable(week_value[[11]],rownames = FALSE)

```

# Week 12

```{r,echo=FALSE}
datatable(week_value[[12]],rownames = FALSE)
```

# Week 13
```{r,echo=FALSE}
datatable(week_value[[13]],rownames = FALSE)

```

# Week 14

```{r,echo=FALSE}
datatable(week_value[[14]],rownames = FALSE)
```


# Week 15
```{r,echo=FALSE}
datatable(week_value[[15]],rownames = FALSE)

```

# Week 16

```{r,echo=FALSE}
datatable(week_value[[16]],rownames = FALSE)
```

# Week 17

```{r,echo=FALSE}
datatable(week_value[[17]],rownames = FALSE)
```

# Week 18
```{r,echo=FALSE}
datatable(week_value[[18]],rownames = FALSE)

```

# Week 19

```{r,echo=FALSE}
datatable(week_value[[19]],rownames = FALSE)
```

# Week 20
```{r,echo=FALSE}
datatable(week_value[[20]],rownames = FALSE)

```

# Week 21

```{r,echo=FALSE}
datatable(week_value[[21]],rownames = FALSE)
```










